plane.penup()
plane.goto(125,-50)
plane.pendown()
plane.color("white")
plane.begin_fill()
plane.pendown()
plane.left(5)
plane.forward(50)
plane.left(-95)
plane.forward(25)
plane.left(-95)
plane.forward(50)
plane.left(95)
plane.forward(25)
plane.pendown()
plane.end_fill()

plane.penup()
plane.goto(125,-50)
plane.pendown()
plane.right(90)
plane.right(5)
plane.forward(25)
plane.color("white")
plane.begin_fill()
plane.pendown()
plane.forward(50)
plane.right(-95)
plane.forward(25)
plane.right(-95)
plane.forward(50)
plane.right(95)
plane.forward(50)
plane.pendown()
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(35,-50)
plane.right(90)
plane.forward(5)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()


plane.penup()
plane.color("blue")
plane.goto(35,-50)
plane.forward(15)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(45,-50)
plane.forward(15)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(45,-50)
plane.forward(5)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(55,-55)
plane.forward(20)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(55,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(65,-55)
plane.forward(20)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(65,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(75,-55)
plane.forward(20)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(75,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(85,-55)
plane.forward(20)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(85,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(95,-55)
plane.forward(20)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.goto(25,-50)
plane.left(5)
plane.forward(25)
plane.color("white")
plane.begin_fill()
plane.pendown()
plane.forward(25)
plane.left(-95)
plane.forward(25)
plane.left(-95)
plane.forward(25)
plane.pendown()
plane.end_fill()